version: '3'
services:
  app:
    image: blog-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/blog
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - blog_network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - blog_data:/var/lib/postgresql/data
    networks:
      - blog_network

networks:
  blog_network:

volumes:
  blog_data:
